#!/bin/sh
set -e

if lb config --help 2>&1 | grep -q -- '--bootloaders'; then
    BOOTLOADER_OPT="--bootloaders"
else
    BOOTLOADER_OPT="--bootloader"
fi

lb config noauto \
    --architectures amd64 \
    --distribution bookworm \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://deb.debian.org/debian" \
    --mirror-chroot "http://deb.debian.org/debian" \
    --mirror-chroot-security "http://deb.debian.org/debian-security" \
    --mirror-binary "http://deb.debian.org/debian" \
    --mirror-binary-security "http://deb.debian.org/debian-security" \
    "$BOOTLOADER_OPT" "grub-pc grub-efi" \
    --bootappend-live "boot=live components persistence splash quiet" \
    --iso-application "Luna OS" \
    --iso-publisher "Luna OS Project" \
    --iso-volume "LUNA-OS" \
    --memtest none \
    --win32-loader false \
    --apt-recommends false \
    --apt-source-archives false \
    --cache-packages false \
    "${@}"
